### ISSUE TITLE
[Bug] Server reports failed to verify certificate

### ISSUE THREAD

**Issue by chierinyan** [metatube-community/jellyfin-plugin-metatube#334]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.512.1925.0

### MetaTube Server Version

1.2.3 (9126becc99dd)

### What OS are you seeing the problem on?

Linux

### Description

Server reports certificate signed by unknown authority.

Note: The URL in the following log is (obviously) NSFW
```
{"error":{"code":500,"message":"Get \"https://gyutto.com/data/item_img/1980/198093/198093.jpg\": GET https://gyutto.com/data/item_img/1980/198093/198093.jpg giving up after 4 attempt(s): Get \"https://image.gyutto.com/data/item_img/1980/198093/198093.jpg\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}}
```

However chrome believes that the certificate is valid.
![](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/71999828/1542f0ad-75fd-4cdf-bfc9-28988e935bbe)

Tried updating ca-certificates in the container, with no luck

### MetaTube Server

```
  metatube:
    image: "metatube/metatube-server"
    container_name: "metatube"
    user: "1000:1000"
    restart: "unless-stopped"
    logging:
      options:
        max-size: "16m"
    ports: ["8200:8080"]
    command: "-dsn /config/metatube.db"
    volumes:
      - "./metatube:/config"
    environment:
      TZ: "Asia/Shanghai"
```

### Jellyfin/Emby Logs

```
{"error":{"code":500,"message":"Get \"https://gyutto.com/data/item_img/1980/198093/198093.jpg\": GET https://gyutto.com/data/item_img/1980/198093/198093.jpg giving up after 4 attempt(s): Get \"https://image.gyutto.com/data/item_img/1980/198093/198093.jpg\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}}
```

### MetaTube Server Logs

```
[GORM] 2024/05/31 11:22:50 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197
[0.340ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "4004925" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/05/31 - 11:23:01 | 500 | 11.238473426s |        10.6.6.1 | GET      "/v1/images/backdrop/AVBASE/4004925?ratio=-1&pos=-1&auto=False&quality=90"
```

### How to Reproduce

Try parse GETCHU-004925
